project_id = "inpfvfyrfhrgkrhbjrwn"

[functions.meta-whatsapp-webhook]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

